version: '1.0'
services:
  backend:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: backend/docker
    container_name: pya-spring
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - PSQL_DB_URL=//db:5432/PYA
      - PSQL_DB_USERNAME=postgres
      - PSQL_DB_PASSWORD=postgres
      - JWT_SECRET=VGhlIHNob3J0IHBvZW0gaXMgbW9yZSBjaGFsbGVuZ2luZyB0byB3cml0ZSB0aGFuIGEgbG9uZ2VyIHBvZW0uIEl0IHNlZWtzIHRvIG1ha2UgZXZlcnkgd29yZCBjb3VudCBhbmQgbWVhbiBleGFjdGx5IHdoYXQgaXMgaW50ZW5kZWQuIEEgc2hvcnQgcG9lbSBoYXMgdGhlIGFkZGVkIGJlbmVmaXQgb2YgZ2V0dGluZyB0aGUgbWVzc2FnZSBvZiBwb2VtIHRocm91Z2ggdG8gdGhlIHJlYWRlciBpbiBhIHN1Y2NpbmN0IHdheS4gVGhlcmUgYXJlIG1hbnkgdHJhZGl0aW9uYWwgc3R5bGVzIG9mIGh1bW9yb3VzIHNob3J0IHBvZW1zLiBUaGUgY2hhbGxlbmdlIGlzIGluIGdldHRpbmcgeW91ciB3b3JkcyBpbnRvIHRoZSBwcm9wZXIgbnVtYmVyIG9mIHN5bGxhYmxlcyBpbiBlYWNoIHN0YW56YS4gVGhlc2UgcG9lbXMgaGF2ZSBhIHRlY2huaWNhbCBlbGVtZW50IHRvIHRoZW0gdGhhdCBjb250cmFzdCB3aXRoIHRoZSBmcmVlIGZsb3dpbmcgcG9lbXMgdGhhdCBhcmUgbW9yZSBjb21tb24gdG9kYXkuQVNUTUFNeXNsaVplSmVzdEZham5hTE9M
    networks:
      - spring-postgres
      - spring-react
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres
    container_name: pya-db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=PYA
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  frontend:
    build:
      context: frontend
    container_name: pya-frontend
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - spring-react
    depends_on:
      - backend
volumes:
  db-data:
networks:
  spring-postgres:
  spring-react: