export const LANGUAGES = {
    "pl" : {
        "About" : "O nas",
        "Team" : "Zespół",
        "Practice" : "Ćwiczenia",
        "Lessons" : "Lekcje",
        "MyAccount" : "Twoje konto",
        "LogOut" : "Wyloguj",
        "LogIn" : "Zaloguj",
        "Username" : "Nazwa użytkownika",
        "Password" : "Hasło",
        "CreateAccount" : "załóż konto",
        "SelectLesson" : "WYBIERZ LEKCJĘ NA DZIŚ",
        "BackToList" : "Powrót do spisu treści",
        "NotSignedIn" : "",
        "SignedIn" : "zalogowany",
        "Logout" : "Jesteś zalogowany",
        "LogedInAs" : "Zalogowany jako",
        "SureToQuit" : "Czy na pewno chcesz się wylogować?",
        "ServerDown" : "Serwer: niedostępny",
        "ServerUp" : "Serwer: OK",
        "SearchLessons" : "Szukaj lekcji",
        "AllLessons" : "Wszystkie lekcje",
        "NotCompleted" : "Nieukończone",
        "Completed" : "UKOŃCZONE",
        "LessonsStatus" : "Stan",
        "CompleteLesson" : "Zakończ lekcję",
        "BackToLessonsList" : "Wróc do listy lekcji",
        "EmailAddress" : "Adres email",
        "DeleteAccount" : "Usuń konto",
        "Error" : "Błąd",
        "SuccessfulDelete" : "Usunięto pomyślnie",
        "SaveChanges" : "Zapisz zmiany",
        "Yes" : "Tak",
        "TeamName" : "Zespół Polish Your English",
        "EnterText" : "Wprowadź tekst",
        "ManageUsers" : "Panel zarządzania użytkownikami",
        "User" : "Użytkownik",
        "UserStatus" : "Status",
        "SwitchUserStatus" : "",
        "UserIsActived" : "Aktywny",
        "UserIsDeactivated" : "Dezaktywowany",
        "Activate" : "Aktywuj",
        "Deactivate" : "Dezaktywuj",
        "GetBackTPrevView" : "Wróć",
        "Register" : "Załóż konto",
        "ErrorsMessages" : {
            "ChatGPT" : "Brak odpowiedzi Chatu, spróbuj ponownie póżniej",
            "failedToActivateUser" : "Nie udało się aktywować użytkownika",
            "failedToDeactivateUser" : "Nie udało się deaktywować użytkownika",
        },
        "ValidationMessages" : {
            "FieldRequired" : "To pole jest wymagane",
            "InvalidMail" : "Niepoprawny mail",
        },
        "RegistrationAlerts" : {
            "UserRegisteredTitle" : "Założono nowe konto",
            "UserRegisteredMsg" : "Możesz się zalogować używając podanych danych",
            "UserAlreadyExistsTitle" : "Użytkownik już istnieje",
            "UserAlreadyExistsMsg" : "Wybierz inną nazwę użytkownika",
            "UserNotRegisteredTitle" : "Nie założono nowego konta",
            "UserNotRegisteredMsg" : "Wystąpił błąd",
            "GenericErrorTitle" : "Błąd",
            "GenericErrorMsg" : "Coś poszło nie tak",
            "InvalidPassword" : "Hasło musi posiadać więcej niż 6 znaków i nie mniej niż 40"
        }
    },

}