export const LANGUAGES = {
    'pl' : {
        'About' : 'O nas',
        'Team' : 'Zespół',
        'Practice' : 'Ćwiczenia',
        'Lessons' : 'Lekcje',
        'MyAccount' : 'Twoje konto',
        'LogOut' : 'Wyloguj',
        'LogIn' : 'Zaloguj',
        'Username' : 'Nazwa użytkownika',
        'Password' : 'Hasło',
        'CreateAccount' : 'załóż konto',
        'SelectLesson' : 'WYBIERZ LEKCJĘ NA DZIŚ',
        'BackToList' : 'Powrót do spisu treści',
        'NotSignedIn' : '',
        'SignedIn' : 'zalogowany',
        'Logout' : 'Jesteś zalogowany',
        'LogedInAs' : "Zalogowany jako",
        'SureToQuit' : 'Czy na pewno chcesz się wylogować?',
        'ServerDown' : 'Server: niedostępny',
        'ServerUp' : 'Server: OK',
        'SearchLessons' : 'Szukaj lekcji',
        'AllLessons' : 'Wszystkie lekcje',
        'NotCompleted' : "Nieukończone",
        'Completed' : "UKOŃCZONE",
        "LessonsStatus" : "Stan",
        "CompleteLesson" : "Zakończ lekcję",
        "BackToLessonsList" : "Wróc do listy lekcji",
        "EmailAddress" : "Adres email",
        "DeleteAccount" : "Usuń konto",
        "Error" : "Błąd",
        "SuccessfulDelete" : "Usunięto pomyślnie",
        "SaveChanges" : "Zapisz zmiany",
        "Yes" : "Tak",
        "TeamName" : "Zespół Polish Your English",
        "EnterText" : "Wprowadź tekst",
        "ManageUsers" : "Panel zarządzania użytkownikami",
        "User" : "Użytkownik",
        "UserStatus" : "Status",
        "SwitchUserStatus" : "",
        "UserIsActived" : "Aktywny",
        "UserIsDeactivated" : "Dezaktywowany",
        "Activate" : "Aktywuj",
        "Deactivate" : "Dezaktywuj",
        "GetBackTPrevView" : "Wróć",
    }
}